---
kind: pipeline
type: docker
name: default

steps:
- name: build
  image: plugins/docker
  settings:
    registry: ghcr.io
    repo: roarkgit/marcel-toing
    username: roarkgit
    password:
      from_secret: github_pat